name: Keep backend awake

on:
  schedule:
    - cron: "*/10 * * * *"  # every 10 minutes (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping health endpoint
        env:
          PING_URL: ${{ secrets.PING_URL }}
        run: |
          if [ -z "$PING_URL" ]; then
            echo "PING_URL is not set"; exit 1;
          fi
          for i in {1..3}; do
            curl -fsS -m 20 -A "gha-keepalive" "$PING_URL" >/dev/null && exit 0
            sleep 10
          done
          echo "Ping failed"; exit 1
